server:
  port: ${SERVER_PORT:8091}
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/user-db}
    driver-class-name: org.postgresql.Driver
    username": ${DB_LOGIN:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      transaction-isolation: TRANSACTION_SERIALIZABLE

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    non-secure-port-enabled: false
    secure-port-enabled: true

app:
  security:
    jwt:
      key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
      expiration: 36000000